
all:
	make -C 2mm all
	make -C 3mm all
	make -C atax all
	make -C bicg all
#	make -C cholesky all
#	make -C doitgen all
#	make -C gemm all
#	make -C gemver all
#	make -C gesummv all
#	make -C mvt all
#	make -C symm all
#	make -C syr2k all
#	make -C syrk all
#	make -C trisolv all
#	make -C trmm all

check:
	make -C 2mm check
	make -C 3mm check
	make -C atax check
	make -C bicg check
#	make -C cholesky check
#	make -C doitgen check
#	make -C gemm check
#	make -C gemver check
#	make -C gesummv check
#	make -C mvt check
#	make -C symm check
#	make -C syr2k check
#	make -C syrk check
#	make -C trisolv check
#	make -C trmm check

clean:
	make -C 2mm clean
	make -C 3mm clean
	make -C atax clean
	make -C bicg clean
#	make -C cholesky clean
#	make -C doitgen clean
#	make -C gemm clean
#	make -C gemver clean
#	make -C gesummv clean
#	make -C mvt clean
#	make -C symm clean
#	make -C syr2k clean
#	make -C syrk clean
#	make -C trisolv clean
#	make -C trmm clean

