
all:
#	make -C durbin all
#	make -C dynprog all
#	make -C gramschmidt all
#	make -C lu all
#	make -C ludcmp all

check:
#	make -C durbin check
#	make -C dynprog check
#	make -C gramschmidt check
#	make -C lu check
#	make -C ludcmp check

clean:
#	make -C durbin clean
#	make -C dynprog clean
#	make -C gramschmidt clean
#	make -C lu clean
#	make -C ludcmp clean

