
all:
	make -C datamining all
	make -C linear-algebra all
	make -C medley all
	make -C stencils all

check:
	make -C datamining check
	make -C linear-algebra check
	make -C medley check
	make -C stencils check

clean:
	make -C datamining clean
	make -C linear-algebra clean
	make -C medley clean
	make -C stencils clean

