
all:
#	make -C adi all
#	make -C convolution-2d all
#	make -C convolution-3d all
#	make -C fdtd-2d all
#	make -C fdtd-apml all
#	make -C jacobi-1d-imper all
#	make -C jacobi-2d-imper all
#	make -C seidel-2d all

check:
#	make -C adi check
#	make -C convolution-2d check
#	make -C convolution-3d check
#	make -C fdtd-2d check
#	make -C fdtd-apml check
#	make -C jacobi-1d-imper check
#	make -C jacobi-2d-imper check
#	make -C seidel-2d check

clean:
#	make -C adi clean
#	make -C convolution-2d clean
#	make -C convolution-3d clean
#	make -C fdtd-2d clean
#	make -C fdtd-apml clean
#	make -C jacobi-1d-imper clean
#	make -C jacobi-2d-imper clean
#	make -C seidel-2d clean

